name: "Style Feature Request"
description: "Sugiere una nueva funcionalidad relacionada con el estilo"
title: "[FEATURE-STYLED] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Solicitud de funcionalidad
        Por favor complet치 los siguientes campos para describir la nueva funcionalidad de estilo.

  - type: textarea
    id: descripcion
    attributes:
      label: "游늯 Descripci칩n"
      description: "쯈ue parte de la app vas a estilar?"
      placeholder: "Ej: P치gina de inicio"
    validations:
      required: true

  - type: textarea
    id: comentarios_adicionales
    attributes:
      label: "游닇 Comentarios adicionales"
      description: " Eeferencias, links, etc.?"
      placeholder: "Ej: Aqu칤 adjunto el dise침o seg칰n figma.com/proyecto, detalles de la paleta de color y recursos..."
    validations:
      required: false